#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║              🧹 CLEANING UP UNUSED CODE & FILES 🧹                     ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

# Backup directory
BACKUP_DIR="backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

echo "📦 Creating backup in: $BACKUP_DIR"
echo ""

# Track what we're removing
REMOVED_COUNT=0

# Function to remove file with backup
remove_file() {
    local file="$1"
    if [ -f "$file" ]; then
        echo "  ❌ Removing: $file"
        cp "$file" "$BACKUP_DIR/" 2>/dev/null
        rm "$file"
        REMOVED_COUNT=$((REMOVED_COUNT + 1))
    fi
}

echo "🗑️  Removing unused template files..."
remove_file "src/main/resources/templates/auction-manage-new.html"
remove_file "src/main/resources/templates/auction-view-new.html"

echo ""
echo "🗑️  Removing disabled backup controller..."
remove_file "src/main/java/com/fantasyia/user/RegistrationController.java"

echo ""
echo "🗑️  Removing redundant documentation files..."
remove_file "AUCTION_CRASH_FIX_V2.md"
remove_file "AUCTION_FIX_README.md"
remove_file "AUCTION_V2_README.md"
remove_file "AUTO_AUCTION_INTEGRATION.md"
remove_file "BUILD_FIX_READY.txt"
remove_file "CRASH_FIX_COMPLETE.md"
remove_file "DATABASE_ACCESS_SUMMARY.txt"
remove_file "DATABASE_CONSTRAINT_FIX.md"
remove_file "DATABASE_MIGRATION_GUIDE.md"
remove_file "DATABASE_MIGRATION_V2.md"
remove_file "DEPLOYMENT_CHECKLIST.md"
remove_file "FIX_500_ERROR.md"
remove_file "FIX_500_ERROR_GUIDE.md"
remove_file "FIX_500_NOW.txt"
remove_file "FIX_500_VISUAL.txt"
remove_file "FIX_COMPLETION_REPORT.md"
remove_file "FIX_CRASH_NOW.txt"
remove_file "FIX_NOW.md"
remove_file "FIX_SUMMARY.md"
remove_file "MASTER_FIX_GUIDE.md"
remove_file "QUICK_FIX_VISUAL.txt"
remove_file "README_FIX_CRASH.md"
remove_file "READY_TO_PUSH.txt"
remove_file "SIMPLE_FIX.txt"

echo ""
echo "🗑️  Removing temporary/redundant shell scripts..."
remove_file "access_db.sh"
remove_file "apply_crash_fix_v2.sh"
remove_file "apply_fix.sh"
remove_file "auto_fix.sh"
remove_file "check_errors.sh"
remove_file "check_tables_exist.sh"
remove_file "commit_auction_changes.sh"
remove_file "commit_auction_rework.sh"
remove_file "commit_changes.sh"
remove_file "commit_excel_import.sh"
remove_file "commit_queue_and_fixes.sh"
remove_file "db_tools.sh"
remove_file "deploy_auction_v2.sh"
remove_file "diagnose_pgadmin_issue.sh"
remove_file "do_commit_push.sh"
remove_file "execute_commit_push.sh"
remove_file "fix-templates.sh"
remove_file "fix_500_error.sh"
remove_file "fix_500_error_v2.sh"
remove_file "fix_complete.sh"
remove_file "fix_crash.sh"
remove_file "nuclear_fix.sh"
remove_file "one_line_fix.sh"
remove_file "quick_db_queries.sh"
remove_file "quick_fix.sh"
remove_file "quick_fix_and_build.sh"
remove_file "restart_app.sh"
remove_file "run_pgadmin_diagnostic.sh"
remove_file "test_auction_fix.sh"
remove_file "test_login_fix.sh"

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                         ✅ CLEANUP COMPLETE! ✅                         ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Summary:"
echo "  • Files removed: $REMOVED_COUNT"
echo "  • Backup location: $BACKUP_DIR"
echo ""
echo "✨ Keeping only essential files:"
echo "  ✓ rebuild.sh - Main build script"
echo "  ✓ rebuild_and_restart.sh - Build and restart Docker"
echo "  ✓ build_complete_fix.sh - Complete fix build"
echo "  ✓ start_docker.sh - Start Docker containers"
echo "  ✓ README.md - Main documentation"
echo "  ✓ AUCTION_MANAGE_FIX.md - Recent fix documentation"
echo "  ✓ FIX_COMPLETE_SUMMARY.txt - Latest fix summary"
echo "  ✓ Core documentation files"
echo ""
echo "🎯 Your codebase is now cleaner and more maintainable!"
echo ""
