-- SQL script to manually create dasGoat commissioner account
-- Run this if the application is already running but missing the dasGoat account

INSERT INTO users (username, password, role, salary_cap, current_salary_used, major_league_roster_count, minor_league_roster_count)
VALUES ('dasGoat', '$2a$10$XYzAbCdEfGhIjKlMnOpQrS.TuVwXyZ123456789EXAMPLE', 'COMMISSIONER', 125.0, 0.0, 0, 0)
ON CONFLICT (username) DO NOTHING;

-- Note: The password above is hashed for 'goat123'
-- In practice, the actual hash will be generated by BCrypt when the DataInitializer runs